### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "firstname": "Ruben",
    "lastname": "Serra",
    "company": "Rubotic",
    "email": "e@2.com",
    "password": "password1234"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json
 
{
   "email": "e@2.com",
   "password": "password1234"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAMi5jb20iLCJpYXQiOjE2NjYxNjM5NjgsImV4cCI6MTY2NjE2NDg2OH0.TvNkK1JcJmsyKWO3nattyPZTW_ye_5pbBxqefuaOuLM

### Get Refresh Token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiZUAyLmNvbSIsImlhdCI6MTY2NjE2Mzk2OCwiZXhwIjoxNjY4NzU1OTY4fQ.SNi8fqWNuwWrh2IKOHtjufzClbV4wSVB3q6Zubno1yw

### Password reset endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
   "email": "e@2.com"
}

### Update new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json
 
{
   "email": "e@2.com",
   "pin": 843430,
   "newPassword": "password2"
}

